<?xml version='1.0'?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="package_name" value="mybot_description"/>
  <xacro:property name="robot_name" value="mybot"/>
  <xacro:property name="lidar_base_radius" value="0.05"/>
  <xacro:property name="lidar_base_height" value="0.05"/>
  <xacro:property name="laz_radius" value="0.04"/>
  <xacro:property name="laz_height" value="0.1"/>

  <xacro:include filename="$(find ${package_name})/urdf/mybot_velodyne.gazebo.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/materials.xacro" />
  
  <link name="link_chassis">
    <!-- pose and inertial -->
    <pose>0 0 0.1 0 0 0</pose>
    
    <inertial>
      <mass value="10.0"/>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <inertia 
        ixx="0.5" ixy="0" ixz="0"
        iyy="1.0" iyz="0" izz="0.1"/>
    </inertial>
    
    
    <!-- body -->
    <collision name="collision_chassis">
      <geometry>
        <box size="0.5 0.3 0.07"/>
      </geometry>
    </collision>
    
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.5 0.3 0.07"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    
    <!-- spherical caster in body front -->
    <collision name="caster_collision">
      <origin rpy=" 0 0 0" xyz="0.2 0 -0.05"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    
    <visual name="caster_visual">
      <origin rpy=" 0 0 0" xyz="0.2 0 -0.05"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
  </link>
  
  <!-- left rear wheel properties -->
  <link name="link_left_wheel">
    <collision name="link_left_wheel_collision">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.1"/>
      </geometry>
    </collision>
    
    <visual name="link_left_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.1"/>
      </geometry>
    </visual>
    
    <inertial>
      <mass value="5"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <cylinder_inertia m="5" r="0.1" h="0.04"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
               iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  
  <!-- right rear wheel properties -->
  <link name="link_right_wheel">
    <collision name="link_right_wheel_collision">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.1"/>
      </geometry>
    </collision>
    
    <visual name="link_right_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.1"/>
      </geometry>
    </visual>
    
    <inertial>
      <mass value="5"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <cylinder_inertia m="5" r="0.1" h="0.04"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
               iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint_left_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="-0.05 -0.17 0"/>
    <child link="link_left_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>
  
  <joint name="joint_right_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="-0.05 0.17 0"/>
    <child link="link_right_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>
  
  <transmission name="left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_left_wheel">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>  
    </joint>
    <actuator name="left_wheel_actuator">
      <mechanicalReduction>7</mechanicalReduction>
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>

  <transmission name="right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_right_wheel">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>  
    </joint>
    <actuator name="right_wheel_actuator">
      <mechanicalReduction>7</mechanicalReduction>
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  
  <!-- controller requires an extra dummy link that nulls the inertia -->
  <link name="dummy">
  </link>
  <joint name="dummy_joint" type="fixed">
     <parent link="dummy"/>
     <child link="link_chassis"/>
   </joint>
   
  <!-- Define sensors and attach them to the vehicle chassis -->   
  
  <!-- =============================== LIDAR =============================== -->
  <link name="laz_base">
    <visual>
      <geometry>
        <cylinder length="${lidar_base_height}" radius="${lidar_base_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${lidar_base_height}" radius="${lidar_base_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.2</mu>
            <mu2>0.2</mu2>
          </ode>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="${(1/12) * 0.1 * (3 * lidar_base_radius * lidar_base_radius + lidar_base_height * lidar_base_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * lidar_base_radius * lidar_base_radius + lidar_base_height * lidar_base_height)}" iyz="0" izz="${(1/2) * 0.1 * lidar_base_radius * lidar_base_radius}"/>
    </inertial>
  </link>

  <link name="laz_rot">
    <visual>
      <geometry>
        <cylinder length="${laz_height}" radius="${laz_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${laz_height}" radius="${laz_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.2</mu>
            <mu2>0.2</mu2>
          </ode>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="${(1/12) * 0.1 * (3 * laz_radius * laz_radius + laz_height * laz_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * laz_radius * laz_radius + laz_height * laz_height)}" iyz="0" izz="${(1/2) * 0.1 * laz_radius * laz_radius}"/>
    </inertial>
  </link>

  <joint name="lazRot" type="continuous">
    <parent link="laz_base"/>
    <child link="laz_rot"/>
    <axis xyz="0 0 1"/>
    <origin xyz = "0 0 ${lidar_base_height/2}"/>
    <dynamics friction="0.1"/>
  </joint>

  <!-- Attach Lidar to the Vehicle Body -->  
  <joint name="base_to_lidar" type="continuous">
    <origin xyz="0 0 0.051" rpy="0 0 0"/>
    <axis xyz="0 0 1" />
    <parent link="link_chassis"/>
    <child link="laz_base"/>
  </joint>
  
  <transmission name="base_to_lidar_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="lidar_actuator">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="base_to_lidar">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
  </transmission>
  
</robot>
